[package]
name = "aoc_2020"
version = "0.1.0"
authors = ["Denaun <mauzuc90@yahoo.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"
num-traits = "0.2"
nom = "6.0"